apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/* #  
build:
  local:
    push: false
  artifacts:
    - image: yeyuhao1234/auth
      context: auth
      docker: 
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.s'
            dest: .
    - image: yeyuhao1234/client
      context: client
      docker: 
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '**/*.js'
            dest: .
    - image: yeyuhao1234/ticket
      context: ticket
      docker: 
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.s'
            dest: .
    - image: yeyuhao1234/order
      context: order
      docker: 
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.s'
            dest: .
    - image: yeyuhao1234/expiration
      context: expiration
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.s'
            dest: .
    - image: yeyuhao1234/payment
      context: payment
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.s'
            dest: .